version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: smartmat
      MYSQL_USER: bjorn
      MYSQL_PASSWORD: passord
      MYSQL_ROOT_PASSWORD: RootPassord
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  mysql-data:
