spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/SmartMat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: bjorn
    password: passord
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
