spring:
  datasource:
    url: jdbc:mysql://mysql-ait.stud.idi.ntnu.no:3306/bjornjob?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: bjornjob
    password: 7Wk7DTGpF
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect