spring:
  datasource:
    url: jdbc:mysql://mysql-ait.stud.idi.ntnu.no:3306/arnoldsh?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: arnoldsh
    password: RoZIXrchM
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

