spring:
  datasource:
    url: jdbc:mysql://mysql-ait.stud.idi.ntnu.no:3306/bjornjob
    username: bjornjob
    password: 7Wk7DTGpF
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect