spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/smartmat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: bjorn
    password: passord
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always

application:
  security:
    jwt:
      secret-key: 452948404D635166546A576E5A7134743777217A25432A462D4A614E64526755
      #expiration: 60000 # 1 minute
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
